export const PREFECTURES = [
  { code: 1, name: '北海道', region: '北海道' },
  { code: 2, name: '青森', region: '東北' },
  { code: 3, name: '岩手', region: '東北' },
  { code: 4, name: '宮城', region: '東北' },
  { code: 5, name: '秋田', region: '東北' },
  { code: 6, name: '山形', region: '東北' },
  { code: 7, name: '福島', region: '東北' },
  { code: 8, name: '茨城', region: '関東' },
  { code: 9, name: '栃木', region: '関東' },
  { code: 10, name: '群馬', region: '関東' },
  { code: 11, name: '埼玉', region: '関東' },
  { code: 12, name: '千葉', region: '関東' },
  { code: 13, name: '東京', region: '関東' },
  { code: 14, name: '神奈川', region: '関東' },
  { code: 15, name: '新潟', region: '中部' },
  { code: 16, name: '富山', region: '中部' },
  { code: 17, name: '石川', region: '中部' },
  { code: 18, name: '福井', region: '中部' },
  { code: 19, name: '山梨', region: '中部' },
  { code: 20, name: '長野', region: '中部' },
  { code: 21, name: '岐阜', region: '中部' },
  { code: 22, name: '静岡', region: '中部' },
  { code: 23, name: '愛知', region: '中部' },
  { code: 24, name: '三重', region: '近畿' },
  { code: 25, name: '滋賀', region: '近畿' },
  { code: 26, name: '京都', region: '近畿' },
  { code: 27, name: '大阪', region: '近畿' },
  { code: 28, name: '兵庫', region: '近畿' },
  { code: 29, name: '奈良', region: '近畿' },
  { code: 30, name: '和歌山', region: '近畿' },
  { code: 31, name: '鳥取', region: '中国' },
  { code: 32, name: '島根', region: '中国' },
  { code: 33, name: '岡山', region: '中国' },
  { code: 34, name: '広島', region: '中国' },
  { code: 35, name: '山口', region: '中国' },
  { code: 36, name: '徳島', region: '四国' },
  { code: 37, name: '香川', region: '四国' },
  { code: 38, name: '愛媛', region: '四国' },
  { code: 39, name: '高知', region: '四国' },
  { code: 40, name: '福岡', region: '九州' },
  { code: 41, name: '佐賀', region: '九州' },
  { code: 42, name: '長崎', region: '九州' },
  { code: 43, name: '熊本', region: '九州' },
  { code: 44, name: '大分', region: '九州' },
  { code: 45, name: '宮崎', region: '九州' },
  { code: 46, name: '鹿児島', region: '九州' },
  { code: 47, name: '沖縄', region: '九州' },
]

export const getPrefectureName = (code: number) =>
  PREFECTURES.find((p) => p.code === code)?.name ?? `都道府県${code}`
